### PR TITLE
Fix normalizr and other test

### PR DESCRIPTION
**Pull request by nickpalmer**

### CODE REVIEW

**Comment by nickpalmer** [comment]
It would seem that c1615a78 did some package upgrades and broke the build. This fixes the issues but bumps minimum node version to 6. If you really intend to continue to support 4 we would need more polyfills. Considering 4 is out of "Active LTS" window and Node 8 is slated to be released in about a month I don't know if you want to make the effort.

**Comment by sdgluck** [comment]
Thanks for this. I'm happy to leave out support for Node v4 in v4.2. Could you add a note in the README along those lines?

**Comment by sdgluck** [comment]
@nickpalmer Bump :-)

**Comment by nickpalmer** [comment]
Sorry. Been super busy on the project I am using Kasia on and haven't had time to circle back to this. Will get this one to mergable today and I think the others will fall out.

**Pull request merged**
